spring.application.name=SpringBootActuator
server.port=8899
#anabled actuator endpoint
management.endpoints.web.exposure.include=health,info,metrics
#add app info
management.info.env.enabled=true
info.app.name=Actuator Demo App
info.app.version=1.0
info.app.description=simple actuator example for fresher